### ISSUE TITLE
Amazon.DayofWeek returns friday instead of Friday.

### ISSUE THREAD

**Issue by ToddMason** [alexa/alexa-skills-kit-sdk-for-java#101]
When receiving slot values for a slot type of Amazon.DayofWeek all the days except Friday return the value with the first letter of the day capitalized. For example Monday, Tuesday, Wednesday, Thursday, Saturday and Sunday all start with a capital letter with the exception of Friday which returns **friday** with the first letter lower case.

## Possible Solution
Make the slot values consistent across all days of the week. Make them all start with a lower case letter or start with a upper case letter.

## Your Environment
I'm using ASK Java SDK 2.0.2

**Comment by brendanclement** [comment]
Hey Todd,

We typically track issues with the SDK on this GitHub.  On anything else we typically advise developers to post on [Alexa user voice](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote)?

I'm closing this for now but I will send a note over internally to the team that owns this slot.

**Comment by ToddMason** [comment]
Thanks! I wasn't sure which place was most appropriate.

**Comment by ToddMason** [comment]
Good point, That change would certainly cause problems for those looking for Friday to be in lower case. Right now I'm converting to lower case to avoid the issue in my skill but I like your idea of creating my own custom slot type better. Thanks again.
