### ISSUE TITLE
use aws lambda to test helloworld samples with this exception

### ISSUE THREAD

**Issue by MitchZhang** [alexa/alexa-skills-kit-sdk-for-java#102]
{
  "errorMessage": "An error occurred during JSON parsing",
  "errorType": "java.lang.RuntimeException",
  "stackTrace": [],
  "cause": {
    "errorMessage": "com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.amazon.ask.dispatcher.request.handler.HandlerInput]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@6536e911; line: 1, column: 2]",
    "errorType": "java.io.UncheckedIOException",
    "stackTrace": [],
    "cause": {
      "errorMessage": "No suitable constructor found for type [simple type, class com.amazon.ask.dispatcher.request.handler.HandlerInput]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@6536e911; line: 1, column: 2]",
      "errorType": "com.fasterxml.jackson.databind.JsonMappingException",
      "stackTrace": [
        "com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)",
        "com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)",
        "com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)",
        "com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)",
        "com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)",
        "com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)"
      ]
    }
  }
}

**Comment by MitchZhang** [comment]
thank you,I try to test my Alexa Skill kit with helloworld sample,than i uplaod the helloworld jar to the aws lambda.when i test the lambda ，This exception happened
--------------------------------------------------------------------
{
"errorMessage": "An error occurred during JSON parsing",
"errorType": "java.lang.RuntimeException",
"stackTrace": [],
"cause": {
"errorMessage": "com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.amazon.ask.dispatcher.request.handler.HandlerInput]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@6536e911; line: 1, column: 2]",
"errorType": "java.io.UncheckedIOException",
"stackTrace": [],
"cause": {
"errorMessage": "No suitable constructor found for type [simple type, class com.amazon.ask.dispatcher.request.handler.HandlerInput]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@6536e911; line: 1, column: 2]",
"errorType": "com.fasterxml.jackson.databind.JsonMappingException",
"stackTrace": [
"com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)",
"com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)",
"com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)",
"com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)"
]
}
}
} 
----------------------------------------------------------------------------
this is my steps:
1. I compile helloworld to a jar (https://github.com/alexa/alexa-skills-kit-sdk-for-java/tree/2.0.x/samples/helloworld)
2.i upload this jar to the aws lambda
3.test lambda in the aws consle
---------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/14865982/39390291-f740b6a4-4ac4-11e8-91f4-b5ac24d6c257.png)

**Comment by nikhilym** [comment]
Please update your issue or add issue comment following [this](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/.github/ISSUE_TEMPLATE.md) template, so that it will be easier for us to investigate. Thanks!!

**Comment by brendanclement** [comment]
Hey Mitch,

When you upload your JAR to lambda you also need to provide a  Fully qualified class name for the handler
![image](https://user-images.githubusercontent.com/1138958/39404859-e5c944f0-4b4f-11e8-959c-1909a62c7ec0.png)

If you're following the tutorial [developing your first skill](https://github.com/alexa/alexa-skills-kit-sdk-for-java/wiki/Developing-Your-First-Skill#implementing-the-skillstreamhandler), ensure that the handler value on the AWS Lambda Console matches the class name of your StreamHandler. For the case of the hello world skill sample, the box should read `com.amazon.ask.helloworld.HelloWorldStreamHandler`
