### ISSUE TITLE
Detailed helloWorld documentation for beginners

### ISSUE THREAD

**Issue by allusai** [alexa/alexa-skills-kit-sdk-for-java#108]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It seems to me that a lot of the people I see at hackathons developing Alexa skills are able to do so using the "copy-paste" method from the numerous Alexa intro tutorials out there. However, when it came time for them to implement anything out of the ordinary, they didn't have a solid foundational knowledge of concepts like states and intents. I think there should be detailed documentation for at least one of the beginner tutorial programs we provide like the "HelloWorld" program in the ReadMe. Something that goes line by line and explains the concepts clearly as well as the most confusing points for a lot of developers.

## Context

Having a handle on the very fundamentals of developing an Alexa skill and what the tutorial code actually means will help reduce the learning curve for first-time developers. This will also allow developers to create Alexa skills that demonstrate better grasp of the resources available in the Alexa SDK.

**Comment by sungolivia** [comment]
Hi there! Was there any particular line or lines in the HelloWorld wiki that was confusing to you or wanted further explanation? If it occurred to you, the it might be similar case for other first time Alexa skill developers!

**Comment by allusai** [comment]
Hello Olivia! Thank you for the quick response. I think what I am hoping could be changed about the guide isn’t really clarifying existing explanations on the wiki which are already very clear, but rather providing more details about how the code works.

For example, as I was going through the “HelloWorld” tutorial, this was one of the first links I happened upon. It was found under the heading “Developing Your First Skill.”
https://github.com/alexa/alexa-skills-kit-sdk-for-java/wiki/Developing-Your-First-Skill

The guide does a great job of explaining what IntentHandlers are and I quickly understood that Alexa was listening for what you wanted to do. Such as wanting “Hello World” to be spoken (HelloWorldIntent) or wanting more help in understanding what the skill was doing (HelpIntent).

However, when I looked at the actual code in each handler, I could not intuitively understand what the code was actually doing. I just accepted that this is syntax that I will never understand and just copy/pasted the code into my file to make the skill work. I feel like not knowing what was happening “behind-the-scenes” deprived me of the ability to really grasp how the code does what it does.

I personally think since this is the landing site for many first-time developers it would be helpful to have a step-by-step walkthrough of what the code was doing. Something like a link called “Read More” next to each of the IntentHandlers so that if you want to dive deeper into the inner workings of the code, you have the ability to do so. All the resources you need will be in one place and you can gain comprehensive understanding on just the wiki instead of having to look through lots of documentation on different websites to understand what a “predicate” is or what a “simple card” is. Personally, having this option would have helped me a lot when I was making my first Alexa skill.

I wrote up some additional information for the “LaunchRequestHandler” as a sample. This is just an example that I wrote in a couple hours, I think I could definitely make this more concise and well-written if you approve of the idea. And if you would prefer not discussing general concepts like “inheritance” and “overriding” but instead focusing on the Alexa-specific concepts, I can do that as well!

Read More about LaunchRequestHandler (example): https://docs.google.com/document/d/1BosHzmRtFCZtr2AB5SUEyz4LLq91Jumdt-sPprb-NsI/edit?usp=sharing

**Comment by allusai** [comment]
Hello Olivia,

Please let me know if you feel that those changes would be too extensive. I could instead work on making smaller changes to the existing documentation if you would like. I just want to make Alexa more accessible to first-time developers!

Sai

**Comment by sungolivia** [comment]
Hey Sai, thanks for your suggestions, we really appreciate it but it would be bit extensive as of now. I can certainly bring it up with the team but in the meantime smaller changes in pull requests would be great!

**Comment by allusai** [comment]
Hello Olivia, definitely! I've been working on smaller changes and I will try to get them to you as soon as possible.

Sai

**Comment by allusai** [comment]
Hello Olivia, I am trying to create a pull request for the changes to the wiki page but I looked online and I still can't figure out how to do it. Is there a way to do this or would it be alright if I just described the changes to you. 

Thank you!
Sai

**Comment by sungolivia** [comment]
Did this [documentation](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) help?

**Comment by allusai** [comment]
I looked at that link, but the issue is that when I fork this project into my repositories, the wiki is not forked along with it. I also attempted to clone the wiki and make changes but Github doesn't let me do "git push" or "git merge" since I don't have access to the master branch. And this [link](http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) describes a way of forking the wiki but it doesn't work due to not having the right level of permissions.

**Comment by allusai** [comment]
Hello Olivia, would you be able to consider my Wiki update request if I just put the snippet of text I want to change here in this issue?

Thank you,
Sai

**Comment by sungolivia** [comment]
Hey Sai, so if you fork it, it wouldn't let you push or merge aside from creating the pull request because we would want to review and merge it. If you are unable to create a pull request then sure you can upload your changes here.

**Comment by allusai** [comment]
Sorry about that Olivia, I still couldn't get it to work. This text file is how I would have updated the "Developing Your First Skill" section. 

When my group was working on our hackathon project, we didn’t really understand what was happening in the `handle` method. Later when we wanted to use cards in our LaunchRequest method to require login authentication through the Alexa app (using Okta as our secure login API), we struggled for a while to figure out how to do that. I think if these lines had been here to explain what withSimpleCard does and link us to the “Cards” section, we would have been able to find a solution much faster. The same goes for clarifying what `reprompt` does.

[Developing-Your-First-Skill.md.zip](https://github.com/alexa/alexa-skills-kit-sdk-for-java/files/2081565/Developing-Your-First-Skill.md.zip)
Change is on Line 46

**Comment by sungolivia** [comment]
Hey Sai, thanks for the little snippet. I was reading it through and where did the below snippet come from? Is there a documentation I can refer to confirm this?
`If the user doesn't respond in 8 seconds, Alexa will reprompt the user with the
message in 'speechText'`.
`

**Comment by allusai** [comment]
Hello Olivia, of course! The file can be found at alexa-skills-kit-sdk-for-java/ask-sdk-core/src/com/amazon/ask/response/ResponseBuilder.java. This is the direct [link](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk-core/src/com/amazon/ask/response/ResponseBuilder.java) to the file, the description you want of `reprompt` is on line 136.

**Comment by sungolivia** [comment]
Hey Sai, I currently made a change on the wiki not exactly specific to Cards only but also to other general Response objects. Feel free to take a look and let me know!

**Comment by allusai** [comment]
Hello Olivia, thank you for making that change, I think the wording is much clearer now. Could I continue to find places where I think the wiki tutorial could be improved?

**Comment by sungolivia** [comment]
For sure, it helps a lot! But could you make pull requests? I think if it's a continual process of updating, pull request would be much more suitable place to do this at!

**Comment by allusai** [comment]
Sure Olivia, I think right now this setting might be turned on which prevents me from creating a pull request for changes to the wiki. I will try and if I can't find a way around this, I'll let you know. Thank you!

<img width="1511" alt="wiki edit restriction" src="https://user-images.githubusercontent.com/29293001/41612588-59ed65c0-73c1-11e8-9096-a8cf29960d4a.png">

**Comment by sungolivia** [comment]
Hey Sai, the reason that setting is turned on is because we have to review the changes before they can be published. So for future documentation updates, please create a new issue per section or page so that we don't have to keep this one open for so long. We are constantly working on better documentation and really appreciate your help!
