### ISSUE TITLE
Invalid Locale Format issue

### ISSUE THREAD

**Issue by ash-at-github** [alexa/alexa-skills-kit-sdk-for-java#111]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Request.getLocale() returns it in the format en-US, instead of en_US

Had raised this issue before here: https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/97
But since it was closed, did not receive a response to the follow-up question

Follow up Question was - Isn't en_US standard Locale format in Java?
https://stackoverflow.com/a/4632943

http://www.oracle.com/us/technologies/java/locale-140624.html

We can try to handle it at our end, but would like to know if there is any plan to move to Java standard format anytime soon?

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:

## Java Info

* Java version used for development:

**Comment by nikhilym** [comment]
Hey @ash-at-github , the Request Locale value is as per the locale information mentioned [here](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#request-locale). Language specific changes to such values would lead to additional documentation and confusion on users' end I suppose.

**Comment by sungolivia** [comment]
Closing this issue as per inactivity but please feel free to reopen if issue persists!
