### ISSUE TITLE
Errors Executing HelloWorld Lambda Function and Alexa Skill

### ISSUE THREAD

**Issue by gburgalum01** [alexa/alexa-skills-kit-sdk-for-java#113]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## Expected Behavior

I'm expecting to be able to run the HelloWorld Alexa skill as well as successfully execute the associated lambda function.

## Current Behavior

I set up the HelloWorld Alexa Skill with the request "tell hello world hi" and ran it to get the input JSON and output JSON.  The error from the execution of the skill is "There was a problem with the requested skill's response."  The output JSON is null.  

I take the input JSON and dump it into a test event for the associated lambda function.  I put a System.out in the HelloWorldStreamHandler constructor and see that get executed when the lambda function is tested.  However, neither the canHandle or handle methods in the HelloWorldIntentHandler class are being fired.  I'm getting the following error from the lambda function handler: 

{
  "errorMessage": "2018-05-31T19:42:15.235Z b689c37c-650a-11e8-8dc5-2ba2256b77aa Task timed out after 3.00 seconds"
}

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
The code is exactly that as provided in the HelloWorld sample directory in the Github repo.

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
Not sure at this point if it's a setup issue or a bug.  This is the first Alexa Skill I've ever tried to run so maybe my configuration is incorrect.  I'm open to suggestions.

## Your Environment

* ASK Java SDK version used: 2.3.1
* Operating System and version: macOS High Sierra

## Java Info

* Java version used for development: 1.8.0_25

**Comment by sungolivia** [comment]
Hey there, in your Lambda, can you increase the timeout and see if you still get the same error? Java code has a cold start on lambda function as you mentioned you are getting error message even with 10 sec time out then better you make it to 30 sec or 1 min and test the code in lambda function.

**Comment by gburgalum01** [comment]
I increased the timeout on the Lambda function from 3s to 10s.  That did the trick!  Thank you very much for the suggestion.
