### ISSUE TITLE
Update Wiki with latest code changes

### ISSUE THREAD

**Issue by anilrobo90** [alexa/alexa-skills-kit-sdk-for-java#114]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Current code in wiki should work with sdk changes.

## Current Behavior

Class path mismatches, code in wiki is not updated as per code in repo.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

None.

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
Update the code in wiki to reflect the changes done in repo

## Context

While following the guide as per wiki there were class path issues.

**Comment by sungolivia** [comment]
Hey there, thanks for letting us know. While we are working on it, it would be helpful if you can point out specific parts of the documentations to make this process faster! Thanks!

**Comment by anilrobo90** [comment]
Inside wiki,
1.HelpIntent handler

Instead of,
import com.amazon.ask.request.Predicates.intentName;
should be,
import static com.amazon.ask.request.Predicates.intentName;

2.CancelandStopIntent handler

Instead of,
import com.amazon.ask.request.Predicates.intentName;
should be,
import static com.amazon.ask.request.Predicates.intentName;

3.SessionEndedRequest handler

Instead Of,
import com.amazon.ask.request.Predicates.requestType;
should be,
import static com.amazon.ask.request.Predicates.requestType;

4.Implementing the SkillStreamHandler

Instead of,
      private static Skill getSkill() {
          return Skills.standard()
                  .addRequestHandlers(new CancelandStopIntentHandler(), new HelloWorldIntentHandler(), new HelpIntentHandler(), new LaunchRequestHandler(), new SessionEndedRequest())
                  .build();
      }

should be,
    private static Skill getSkill() {
        return Skills.standard()
                .addRequestHandlers(
                        new CancelandStopIntentHandler(),
                        new HelloWorldIntentHandler(),
                        new HelpIntentHandler(),
                        new LaunchRequestHandler(),
                        new SessionEndedRequestHandler())
                // Add your skill id below
                //.withSkillId("")
                .build();
    }

These are the changes I have done in order for the example to work.

**Comment by sungolivia** [comment]
Hey there, changes have been made into the wiki so closing this issue now. Thanks!
