### ISSUE TITLE
ResponseBuilder trimOutputSpeech "<speak>" trimming

### ISSUE THREAD

**Issue by asymptotik** [alexa/alexa-skills-kit-sdk-for-java#116]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The trimOutputSpeech method of the ResponseBuilder class is meant to trim the "<speak>" tags from the input. However, there is an error in:
<code>if (trimmedOutputSpeech.startsWith("&lt;speak&gt;") && trimmedOutputSpeech.endsWith("&lt;/speak&gt;")) {
            return trimmedOutputSpeech.substring(8, trimmedOutputSpeech.length() - 8).trim();
        }
</code>
The error is at the substring call with starting index of 8. The "&lt;speak&gt;" string only has 7 characters and a string has a starting index of 0. The character to the right of the ">" has an index of 7, not 8.

## Expected Behavior

When setting ssml with the ResponseBuilder withSpeech method, the passed string should be able to contain enclosing &lt;speak&gt; markup. 

The trimOutputSpeech method should only trim the &lt;speak&gt; tags and not any of the content.

## Current Behavior

Any character to the right of an opening &lt;speak&gt; tag is trimmed.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Context

Wasted my time tracking it down.

## Your Environment

* ASK Java SDK version used: 8.x.x
* Operating System and version: mac os 10.12.6

## Java Info

* Java version used for development:

**Comment by sungolivia** [comment]
Closing this issue as the pull request above has been created addressing this bug. Please feel free to reopen if this bug persists.

**Comment by breedloj** [comment]
Version 2.3.2 has been released containing this fix. Thanks again for reporting!
