### ISSUE TITLE
How can I retrieve and save persistence attributes with SDK 2.0?

### ISSUE THREAD

**Issue by zHPhil93** [alexa/alexa-skills-kit-sdk-for-java#118]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
Is there any documentation, example project or tutorial how to set up the DynamoDB for easy saving and retrieving of persistence attributes? I already added the following to my SkillStreamHandler:
`.withTableName("xxx")
        		 .withAutoCreateTable(true)`
If i want to save my persistenceAttributes i get the following error: 
`One or more parameter values were invalid: Missing the key userId in the item (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 7BNHLTAIIPBAE1KDK3I7F8ELN7VV4KQNSO5AEMVJF66Q9ASUAAJG)`

I also am not able to retrieve the persistenceAttributes (i guess that is reasonalbe as i have not been able to save any).

## Your Environment

* ASK Java SDK version used: 2.3.1
* Operating System and version: - 

## Java Info

* Java version used for development: 1.8

**Comment by sungolivia** [comment]
Hey there, could you share your piece of code block where you are trying to save/retrieve your persistence attributes? It could help us to help you with more context!

**Comment by breedloj** [comment]
Hey, I just tested this in a test skill and was able to successfully save the attributes. My skill setup looks like this (modified Hello World example):

```
    private static Skill getSkill() {
        return Skills.standard()
                .addRequestHandlers(
                        new CancelandStopIntentHandler(),
                        new HelloWorldIntentHandler(),
                        new HelpIntentHandler(),
                        new LaunchRequestHandler(),
                        new SessionEndedRequestHandler())
                // Add your skill id below
                //.withSkillId("")
                .withTableName("foo")
                .withAutoCreateTable(true)
                .build();
    }
```

And in my handler:
```
        Map<String, Object> persistentAttributes = new HashMap<String, Object>();
        persistentAttributes.put("userId", "xxx"); 
        input.getAttributesManager().setPersistentAttributes(persistentAttributes);
        input.getAttributesManager().savePersistentAttributes();
```

The error you're getting leads me to believe that the table you're targeting may be configured against a userId primary key, whereas by default the SDK uses 'id'. This is configurable if you directly construct a persistence adapter instance, but the easiest solution would be to delete the existing table and let the SDK auto create one that is properly configured.

**Comment by zHPhil93** [comment]
Hey. Thank you for your help. Changing the primary key of the table or deleting the table in DynamoDB really fixed this for me. 
I initially set "userId" as the primary key, because i found some older projects about persistence on alexa which needed that value as primary key. I guess you could update your documentation a bit, but my problem is fixed.
Thanks for the quick help 👍
