### ISSUE TITLE
Input Events are not parsed by model

### ISSUE THREAD

**Issue by ts8ta** [alexa/alexa-skills-kit-sdk-for-java#121]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

SDK 2.0: Input Events of Echo Buttons are not provided in RequestEnvelope correctly.

If you press a button, the incoming event object does not match the structure of json and values if InputEvents are all null. Since the model is not public, I cannot extend the model myself in an appropriate way. 

Please fix, we need this as soon as possible.  

Details:
## Expected Behavior
Example flow is described here: https://developer.amazon.com/de/docs/gadget-skills/discover-echo-buttons.html
When I press an Echo Button, I should receive an event containing information about the buttons pressed. 

## Current Behavior
I am receiving an event with a request of type GameEngine.InputHandlerEvent but the data for Input Events is not filled in Java. 
Checking the json sent to my service, I can see that the data is included. 

## Steps to Reproduce (for bugs)
Implement the example of https://developer.amazon.com/de/docs/gadget-skills/discover-echo-buttons.html with sdk version 2.3.2 and notice that the data is not filled into java objects

## Possible Solution
I think the model is not parsing the relevant information right now, so the model needs to be updated. 

## Context
I am trying to build a game with Echo Buttons but cannot get the buttons, so I cannot build my game. 

## Your Environment

* ASK Java SDK version used: 2.3.2

## Java Info

* Java version used for development: 1.8

**Comment by sungolivia** [comment]
Hi there, do you mind trying to fill out the issue template as much as possible? Even snippets of code showing what you are trying to do, SDK version helps a lot as well and may get this issue resolved faster while we are working on it. Thanks!

**Comment by ts8ta** [comment]
Hi @sungolivia I updated my description above. Let me know if you need more information on this
Thanks!

**Comment by sungolivia** [comment]
Hey @ts8ta, this issue should be fixed with release #[2.3.4 ](https://github.com/alexa/alexa-skills-kit-sdk-for-java/releases/tag/2.3.4). Closing this issue but feel free to reopen if bug is still there!

**Comment by ts8ta** [comment]
Hi @sungolivia I can confirm this is working now using #2.3.4
Thanks!

**Comment by ts8ta** [comment]
Hey @sungolivia sorry, but I need to reopen this. In my test app, I can see that the values are set correctly, but there are not getters to read those from Request (com.amazon.ask.model.Request)

Could you please check any maybe re-open?

**Comment by breedloj** [comment]
Request is generic. If you've written a handler that works against incoming InputHandlerEventRequests you'll want to cast the request to that type to get access to its methods. This is what I did when testing this out yesterday.

**Comment by ts8ta** [comment]
yep, this works. Thanks @breedloj
