### ISSUE TITLE
1.x to 2.x upgrade guide?

### ISSUE THREAD

**Issue by johan12345** [alexa/alexa-skills-kit-sdk-for-java#123]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I noticed that version 2.0 was released a few months ago, and it seems to have many breaking API changes. However, I couldn't find any documentation on how to upgrade existing code based on the `Speechlet` API to the new version.

**Comment by sungolivia** [comment]
Hey there, this is a great suggestion, I will definitely bring it back to the team and let you know! Thanks!

**Comment by sungolivia** [comment]
Closing this issue as there is a [migration guide](https://alexa-skills-kit-sdk-for-java.readthedocs.io/en/latest/Migrating-To-ASK-SDK-v2-For-Java.html) live in documentation!

**Comment by johan12345** [comment]
Great, thanks!
