### ISSUE TITLE
Documentation Request (SkillStreamHandler)

### ISSUE THREAD

**Issue by allusai** [alexa/alexa-skills-kit-sdk-for-java#124]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I am submitting a documentation issue for the "Developing Your First Skill" page. I believe that the wording for the section describing the `SkillStreamHandler` could be improved to make the role of this handler clearer. Also, since the primary handler for the AWS Lambda function can be written in several ways, it would help the reader to know that they might see other implementations too. 

Currently, the wiki says "The stream handler is the entry point for your AWS Lambda function. The following stream handler extends the SDK SkillStreamHandler class provided in the SDK, which routes all inbound requests to our skill. The HelloWorldStreamHandler creates an SDK Skill instance configured with the request handlers we just created."

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
I believe if the following was used, it would simplify the description of the `SkillStreamHandler`. 

"The stream handler is the entry point for your AWS Lambda function. Every request spoken
to Alexa will pass through here first and be forwarded to the appropriate handler (`HelloWorldIntentHandler`, `HelpIntentHandler`, and so on). This is the gate which all requests must travel through before reaching your intent handlers. There are many ways to implement a primary stream handler, here we choose to implement the `SkillStreamHandler` class included in the SDK. The `getSkill` method will add each of the handlers we have previously written to the list of possible destinations of the incoming request."

Thank you!
Sai

**Comment by sungolivia** [comment]
Hey @allusai, thanks for your suggestion! As these wikis were gone through extensive review by teams, I will bring it back to them for review and let you know!

**Comment by allusai** [comment]
Of course, thank you Olivia!

Best Regards,
Sai

**Comment by Taylomol001** [comment]
For what it's worth, as a beginner at Alexa programming, @allusai's suggestion just solved about 10 different questions I had in one paragraph, so I definitely agree that his edits would be very helpful here.

Best,
Molly

**Comment by allusai** [comment]
Thank you so much Molly, that means a lot to me! I’m glad I could help!

Best,
Sai

**Comment by breedloj** [comment]
Hey Sai, thanks for the suggestions! I've incorporated your ideas into a rewritten section describing the purpose of the stream handler. I'm hoping it will be a lot more useful now. Thanks again!
