### ISSUE TITLE
Signature validation failing if order of nodes are modified

### ISSUE THREAD

**Issue by priyadarsh** [alexa/alexa-skills-kit-sdk-for-java#38]
Not sure if this is a issue. However wanted to raise it as I wasted time figuring it out the root cause.

I am using `SpeechletRequestSignatureVerifier` class to verify signature in my Dropwizard application.
- Initially I tried to implement Signature validation as runtime annotation processor at Resource  level. It failed because the InputStream is already consumed and not available in the `HttpServletRequest`. 

- Then I have Implemented a filter like the one below.

```
    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        String requestBody = IOUtils.toString(requestContext.getEntityStream());
        SpeechletRequestSignatureVerifier.checkRequestSignature(requestBody.getBytes(),
                requestContext.getHeaderString("Signature"),
                requestContext.getHeaderString("SignatureCertChainUrl");
        requestContext.setEntityStream(IOUtils.toInputStream(requestBody));
    }
```

Even then it didn't work. Because I was using Junit test case to test it and the Json nodes are jumbled somehow in my test case. 
Not sure if there is a way to fix it because signature is based on the byte array.

**Comment by sungolivia** [comment]
Hey there, this is expected behavior because we need to consume the incoming request before doing any signature validation.
