### ISSUE TITLE
shouldEndSession cannot be null for VideoApp.Launch when used with ServletSpeechletRequestHandler

### ISSUE THREAD

**Issue by nathankopp** [alexa/alexa-skills-kit-sdk-for-java#53]
I'm trying to use VideoApp.Launch with ServletSpeechletRequestHandler
The call to handleSpeechletCall() always returns bytes containing shouldEndSession flag.
Even if I call setNullableShouldEndSession(null), the serialized output still contains the flag. I'm pretty sure that's because it is using the getter for serialization, and the getter always returns a value (see lines 67-69 in SpeechletResponse).

"error":{"type":"INVALID_RESPONSE","message":"shouldEndSession flag is not allowed with LaunchVideoApp.Launch Directive"}}}

**Comment by breedloj** [comment]
This was fixed in SDK v1.4.1. Closing.
