### ISSUE TITLE
Resolutions from Slot

### ISSUE THREAD

**Issue by derda-niel** [alexa/alexa-skills-kit-sdk-for-java#59]
Can not find a way to get the Resolutions from a Slot object! Ther is no function like getResolution() or so. Is there a way to get the Resolution subtree from json without building my own parser?

Thanks.

**Comment by Vest** [comment]
It seems that this feature is not available in Java SDK: [When will the Alexa Java SDK be updated for Entity Resolution](https://forums.developer.amazon.com/questions/76353/when-will-the-alexa-java-sdk-be-updated-for-entity.html).
This is everything I know.

For others, this is a missing feature: [Announcing Alexa Entity Resolution](https://developer.amazon.com/blogs/alexa/post/5de2b24d-d932-4c6f-950d-d09d8ffdf4d4/entity-resolution-and-slot-validation)

**Comment by shad00m** [comment]
This is not implemented yet? But I'Ve seen people using it already for example here: https://forums.developer.amazon.com/questions/76612/synonyms-not-resolving-to-canonical-slot-values-is.html

But I never get that "resolutionsPerAuthority" in the JSON.

**Comment by sebastiande** [comment]
I've added slot entity resolution here: 
https://github.com/amzn/alexa-skills-kit-java/pull/64

**Comment by sungolivia** [comment]
In 2.0.x version of the SDK, there is a method called "getResolutions()" for Slot!
