### ISSUE TITLE
State handling

### ISSUE THREAD

**Issue by paulschuetz** [alexa/alexa-skills-kit-sdk-for-java#81]
Is there a way to manage state within a session in java similar to the node.js sdk? Or has anybody else yet implemented their own state handling/management? Right now everything the user of my skill says will invoke an intent reardless of the point in conversation the user is in. For example if the user is currently interacting with functionality A of my skill he should not be able to invoke intents related to functionality B.

**Comment by janknobloch** [comment]
I used a state variable as an attribute which is passed along my session. maybe this helps?
as of 2.x:

`input.getRequestEnvelope().getSession().getAttributes().put("MY_STATE", "MY_CURRENT_STATE");`

**Comment by sungolivia** [comment]
You can also make use of Attributes Manager for this as well as of 2.0.x!
`        Map<String, Object> sessionAttributes = input.getAttributesManager().getSessionAttributes();
`
Please feel free to reopen this if you still have questions about state handling!
