### ISSUE TITLE
SDK 2.0: Support for Notifications API

### ISSUE THREAD

**Issue by mariokorte** [alexa/alexa-skills-kit-sdk-for-java#84]
SDK 2.0: Please add support for the notifications API.

**Comment by sungolivia** [comment]
Thanks for bringing this to our attention, I will make sure to bring it up with the team!

**Comment by sungolivia** [comment]
Thank you for your feature request, please pitch in ideas to [User Voice](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote?category_id=322783). If it already exists, make sure to give your vote!
