### ISSUE TITLE
SDK 2.0: When using DynmoDB with auto create table first read in session fails

### ISSUE THREAD

**Issue by mariokorte** [alexa/alexa-skills-kit-sdk-for-java#85]
SDK 2.0: I configured the skill with DynamoDB and autoCreateTable set to true. The first read from the db in a session fails (returning a null value), all subsequent reads are working fine.

In the logs I can see that the skill is trying to create the table every time, which fails when it already exists. It seems to me that when this happens the read fails too.

When setting autoCreateTable to false this does not happen.

**Comment by breedloj** [comment]
Thanks for reporting this issue. This has been resolved in the [2.0.2](https://github.com/alexa/alexa-skills-kit-sdk-for-java/releases/tag/2.0.2) release of the SDK.
