### ISSUE TITLE
developing skill without aws

### ISSUE THREAD

**Issue by walter375** [alexa/alexa-skills-kit-sdk-for-java#95]
this command  mvn exec:java -Dexec.executable="java" -DdisableRequestSignatureCheck=true
 leads to the following error (the first build mvn assembly:assembly -DdescriptorId=jar-with-dependencies package was successfull):

log4j:WARN Error during default initialization
java.lang.NoClassDefFoundError: com/amazonaws/services/lambda/runtime/LambdaRuntime
	at com.amazonaws.services.lambda.runtime.log4j.LambdaAppender.<init>(LambdaAppender.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:337)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getRootLogger(Logger.java:135)
	at org.apache.log4j.BasicConfigurator.configure(BasicConfigurator.java:46)
	at Launcher.main(Launcher.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.lambda.runtime.LambdaRuntime
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

we use the following sdk  java version 1.6.0, which contains the Launcher class
Could someone help us?

**Comment by sungolivia** [comment]
Can you paste your pom.xml?

**Comment by walter375** [comment]
that's my pom.xml file 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>alexa-skills-kit-samples</groupId>
  <artifactId>alexa-skills-kit-samples</artifactId>
  <packaging>jar</packaging>
  <version>1.0</version>
  <name>Alexa Skills Kit Samples</name>
  <url>http://developer.amazon.com/ask</url>

  <repositories>
    <repository>
      <id>alexa-skills-kit-repo</id>
      <url>file://${project.basedir}/repo</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>com.amazon.alexa</groupId>
      <artifactId>alexa-skills-kit</artifactId>
      <version>1.3.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
      <version>9.0.6.v20130930</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-servlet</artifactId>
      <version>9.0.6.v20130930</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.17</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.10</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.10</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.directory.studio</groupId>
      <artifactId>org.apache.commons.io</artifactId>
      <version>2.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-core</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-log4j</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-dynamodb</artifactId>
      <version>1.9.40</version>
    </dependency>
  </dependencies>

  <properties>
    <property name="disableRequestSignatureCheck" value="false"/>
    <property name="supportedApplicationIds" value=""/>
    <property name="timestampTolerance" value="150"/>
  </properties>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.3</version>
          <configuration>
            <source>1.7</source>
            <target>1.7</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId> 
         <version>1.2.1</version>
          <configuration>
	    <java classname="Launcher"
		  classpathref="/var/www/alexa/alexa-skills-kit-sdk-for-java-1.6.0" fork="true">
	      <sysproperty key="javax.net.ssl.keyStore"
			   value="/etc/apache2/ssl/java-keystore.jks" />
	      <sysproperty key="javax.net.ssl.keyStorePassword"
			   value="" />
	    </java>
            <mainClass>Launcher</mainClass>
            <systemProperties>
              <systemProperty>
                <key>javax.net.ssl.keyStore</key>
                <value>/etc/apache2/ssl/java-keystore.jks</value>
              </systemProperty>
              <systemProperty>
                <key>javax.net.ssl.keyStorePassword</key>
                <value>HERE IS MY PW</value>
              </systemProperty>
              <systemProperty>
                <key>com.amazon.speech.speechlet.servlet.disableRequestSignatureCheck</key>
                <value>${disableRequestSignatureCheck}</value>
              </systemProperty>
              <systemProperty>
                <key>com.amazon.speech.speechlet.servlet.supportedApplicationIds</key>
                <value>${supportedApplicationIds}</value>
              </systemProperty>
              <systemProperty>
                <key>com.amazon.speech.speechlet.servlet.timestampTolerance</key>
                <value>${timestampTolerance}</value>
              </systemProperty>
            </systemProperties>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>

**Comment by walter375** [comment]
Thats my pom.xml

[pom.pdf](https://github.com/alexa/alexa-skills-kit-sdk-for-java/files/1910207/pom.pdf)

**Comment by sungolivia** [comment]
Hey @walter375 sorry about getting back so late. Do you still have this particular issue? For reference, there is a [Hello World Servlet](https://github.com/alexa/alexa-skills-kit-sdk-for-java/tree/2.0.x/samples/helloworldservlet) sample that could help just in case.

**Comment by breedloj** [comment]
This is a classpath issue. The class it's complaining about should come from the aws-lambda-java-core Maven dependency. I see that it's in your POM but I am not too familiar with spinning things up with the Maven exec plugin. You might try adding `-Dexec.classpathScope=compile` at the end of your command. Given the inactivity here I am going to close it for now, but feel free to reopen if you are still having this issue. Also, I'd give the 2.0.x SDK a shot since the Lambda dependency is no longer forced on you if you depend on the ask-sdk-core module directly.
