### ISSUE TITLE
Invalid Locale Format issue

### ISSUE THREAD

**Issue by ash-at-github** [alexa/alexa-skills-kit-sdk-for-java#97]
Request.getLocale() returns it in the format en-US, instead of en_US
## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: 2.0.2
* Operating System and version:

## Java Info

* Java version used for development:

**Comment by sungolivia** [comment]
Hi there, please refer to supported Alexa [list](https://developer.amazon.com/docs/custom-skills/develop-skills-in-multiple-languages.html#h2-code-changes) of locale properties as en_US is not a part of that list.
